import assert from 'node:assert/strict';
import { randomBytes, createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient, PutCommand, GetCommand, DeleteCommand } from '@aws-sdk/lib-dynamodb';
import { runtimeConfigSchema } from '../shared/runtime-config';

// Uses only invitations generated by this run; no real guest records.
// Configured organizers also receive notifications for these test responses.
const outputs = JSON.parse(await readFile('cdk-outputs.json', 'utf8')).WeddingInvitation;
const db = DynamoDBDocumentClient.from(new DynamoDBClient({ region: process.env.AWS_REGION || 'ap-northeast-1' }));
const keys: string[] = [];
const input = { attendance: 'attending', name: '動作確認用テスト', kana: 'どうさかくにんようてすと', email: '', allergies: '', message: 'Deployment verification', consent: true, website: '' };
let rsvpEndpoint: string;
const post = (body: unknown) => fetch(rsvpEndpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body), signal: AbortSignal.timeout(20000) });
async function createInvite() {
  const token = randomBytes(32).toString('base64url');
  const digest = createHash('sha256').update(token).digest('hex');
  const pk = `INVITE#${digest}`;
  keys.push(pk, `RSVP#${digest}`);
  await db.send(new PutCommand({ TableName: outputs.TableName, Item: { pk, guestName: '__DEPLOYMENT_SMOKE_TEST__', expiresAt: Math.floor(Date.now() / 1000) + 3600, disabled: false }, ConditionExpression: 'attribute_not_exists(pk)' }));
  return { token, responsePk: `RSVP#${digest}` };
}
try {
  const config = runtimeConfigSchema.parse(await fetch(`${outputs.WebsiteUrl}/config.json`, { cache: 'no-store' }).then(res => res.json()));
  assert.equal(config.demo, false);
  assert.equal(config.rsvpEndpoint, outputs.RsvpEndpoint);
  rsvpEndpoint = config.rsvpEndpoint;
  console.log('PASS: production runtime configuration');
  const first = await createInvite();
  assert.equal((await post({ ...input, token: first.token })).status, 201);
  const { Item: stored } = await db.send(new GetCommand({ TableName: outputs.TableName, Key: { pk: first.responsePk }, ConsistentRead: true }));
  assert.equal(stored?.email, '');
  assert.equal(stored?.name, input.name);
  assert.equal((await post({ ...input, token: first.token })).status, 200);
  assert.equal((await post({ ...input, token: first.token, attendance: 'declining' })).status, 409);
  assert.equal((await post({ ...input, token: randomBytes(32).toString('base64url') })).status, 403);
  console.log('PASS: optional-email registration, persistence, duplicate protection, invalid invite');
  const second = await createInvite();
  assert.equal((await post({ ...input, token: second.token, email: 'success@simulator.amazonses.com' })).status, 201);
  let accepted = false;
  for (let attempt = 0; attempt < 45; attempt++) {
    const { Item: response } = await db.send(new GetCommand({ TableName: outputs.TableName, Key: { pk: second.responsePk }, ConsistentRead: true }));
    if (response?.guestMailSent) { accepted = true; break; }
    await new Promise(resolve => setTimeout(resolve, 2000));
  }
  assert.equal(accepted, true, 'SES simulator copy was not marked as sent within 90 seconds');
  console.log('PASS: asynchronous SES copy accepted for AWS mailbox simulator');
} finally {
  for (const pk of keys) await db.send(new DeleteCommand({ TableName: outputs.TableName, Key: { pk } }));
  console.log('Cleaned up this run’s temporary invitation and response records.');
}
